applications:
  - id: 1110001
    name: 组织信息
    app_type: LayoutCol2x
    menu_pid: 10
    menu_order: 1
    funcs:
      - code: O1110000
      - code: O1110001
      - code: O1110002
      - code: O1110003
      - code: O1110004

  - id: 1110002
    name: 组织操作
    funcs:
      - code: O1110005
      - code: O1110006
      - code: O1110007
      - code: O1110008

  - id: 1110003
    name: 组织操作历史
    funcs:
      - code: O1110009

  - id: 1110004
    name: 岗位信息
    menu_pid: 10
    menu_order: 2
    funcs:
      - code: O1110010
      - code: O1110011
      - code: O1110012
      - code: O1110013

  - id: 1110005
    name: 岗位操作
    funcs:
      - code: O1110014
      - code: O1110015
      - code: O1110016

  - id: 1110006
    name: 岗位操作历史
    funcs:
      - code: O1110017

  - id: 1120001
    name: 员工信息
    menu_pid: 11
    menu_order: 1
    funcs:
      - code: E1120001
      - code: E1120002
      - code: E1120003
      - code: E1120004
      - code: E1120005

  - id: 1120002
    name: 事务管理
    menu_pid: 11
    menu_order: 2
    app_type: S_Guide
    funcs:
      - code: E1120006
      - code: E1120008
      - code: E1120015
      - code: E1120017
      - code: E1120019
      - code: E1120021

  - id: 1120003
    name: 合同管理
    menu_pid: 11
    menu_order: 3
    app_type: S_Guide
    funcs:

  - id: 1120004
    name: 兼任管理
    menu_pid: 11
    menu_order: 4

  - id: 1120005
    name: 背景信息
    menu_pid: 11
    menu_order: 5

  - id: 1120006
    name: 失信人员
    menu_pid: 11
    menu_order: 6

  - id: 1120007
    name: 员工档案
    menu_pid: 11
    menu_order: 7

  - id: 1120008
    name: 常用提醒
    menu_pid: 11
    menu_order: 8




